### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by haizeiwanglf** [alipay/YiJian-Community#5]
请问可以提供下transformer版本吗，attack_txt2img_pipeline.py中四个模型各种错误

**Comment by pipiPdesu** [comment]
可以尝试transformers=4.44.2

**Comment by haizeiwanglf** [comment]
请问如何改为多卡呢，我直接改为auto好像不行
        self.txt2img_zh = HFTxt2ImgInfer(
            model_path=txt2img_zh_model,
            pipe=KolorsPipeline,
            variant="fp16",
            cuda_device="cuda:1",
        )
